version: 0.0
os: centos

files:
  - source: .target/webApplication-0.0.1-SNAPSHOT.jar
    destination: /var

hooks:
  BeforeInstall:
   - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
   - location: ./afterInstallation.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./applicationStart.sh
     timeout: 180
     runas: centos