version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/circle-tmp-folder
    steps:
      - checkout
      - run:
          name: Build Artifact
          command: |
            cd webapp
            mvn install
            cd target
            ls -al
            cd ../../..
      - run:
          name: Zip Artifact
          command: |
            echo "Hello current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            ls -al
            mkdir -p codedeploy_artifact
            cp infrastructure/aws/codedeploy/*.sh .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip webapp/target/webApplication-0.0.1-SNAPSHOT.jar *.sh *.yml
            ls -al
            mv csye6225-web-app-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            ls -al
            pwd
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
  deploy:
    machine:
      enabled: true
    working_directory: ~/circle-tmp-folder
    steps:
      - run:
          name: Deploy
          command: |
            aws s3 sync csye6225-web-app-${CIRCLE_BUILD_NUM}.zip s3://app-jar-ec2
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello CodeDeploy" 